version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    redis:
        image: 'redis:alpine'

    mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - '~/hamirror:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=thisisatest
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - '3306:3306'

    clickhouse:
        image: 'yandex/clickhouse-server:latest'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '~/hamirror:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '~/hamirror:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
